theme: jekyll-theme-cayman
title: Max Carter
logo: Headshot.jpeg
description: Researcher in pure mathematics, specialising in topological group theory and operator algebras.                                                                                                                                                                
