theme: jekyll-theme-minimal
title: Max Carter
logo: Headshot.jpeg
description: Email: max.carter.math@gmail.com  Office: SR Social Sciences Building, University Drive, Callaghan, NSW, 2308, Australia
