theme: jekyll-theme-minimal
title: Max Carter
logo: Headshot.jpeg
description: Email - [max.carter@newcastle.edu.au](max.carter@newcastle.edu.au)       Social Sciences Building,            University of Newcastle,        Callaghan, NSW, 2308, Australia                                                                                                                                                                
