theme: jekyll-theme-cayman
title: Max Carter
description: Postgraduate research student in pure mathematics, specialising in topological group theory and operator algebras.   
github:
  is_project_page: false
