theme: jekyll-theme-minimal
title: Max Carter
logo: Headshot.jpeg
description: Email - max.carter.math@gmail.com        School of Mathematical and Physical Sciences,            University of Newcastle,        Callaghan, NSW, 2308, Australia
